### ISSUE TITLE
Request : Provide default ThreadPools with more meaning

### ISSUE THREAD

**Issue by wblancqu** [dabla/parallel-iterable#1]
Your code does exactly what java 8 does with parallelStream. parallelStream uses ForkJoinExecutor. 

You might simulate the same behavior by creating a fixed size ThreadPool using number of cores in your system (int cores = Runtime.getRuntime().availableProcessors()).

rxJava uses Schedulers for this, which allow you to include "Schedulers" in your process (making it concurrent, not parallel). How about the following:

ParallelIterable.from(...).using(ThreadPool.computation()).filter blabla. Have a look at http://reactivex.io/documentation/scheduler.html

**Comment by dabla** [comment]
You can pass your own (fixed threadpool) executor if you want via the ParallelIterable builder which actually replaces the default static cached threadpool executor using the on method.  Maybe I should rename it like in RXjava to using which is more appropriate (naming chapter clean code) ;-) Thx for the input I will look into it!

**Comment by wblancqu** [comment]
Aaaah, didn't see that one... Apart from that, you might really like rxJava ;-)

**Comment by dabla** [comment]
No problem it's my bad I should document it.  I will rename the "on" method though as "using" is more meaningful! Yes I already followed a tutorial on it, it's more flexible and elegant API.  But as we were already heavily using Guava transformations and filtering in our project, it was a easy way to boost performance.  And it did perform well, one part went from multiple hours to 5 minutes, the other part from multiple days to one hour and a half! :-)

**Comment by wblancqu** [comment]
Nice!
